{
 "title": "Twixor Nginx Statistics Copy",
 "description": "Dashboard for Nginx Statistics.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nginx_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "400 ERRORS",
   "type": "timeseries",
   "description": "Total number of GET requests that returned 404 Not Found from NGINX.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "round(increase(nginx_http_response_count_total{status=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of HTTP requests",
   "type": "timeseries",
   "description": "Total HTTP Get and Post requests received by NGINX.\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nginx_http_response_count_total[1m]) * 60",
     "legendFormat": "__auto",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Handling Connections",
   "type": "timeseries",
   "description": "Shows how NGINX is handling client connections: reading requests, sending responses, and idle waiting.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "round(increase(nginx_connections_handled[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 ERRORS",
   "type": "timeseries",
   "description": "This metric counts how many HEAD requests NGINX has responded with 404 Not Found.”\n\nWhy it’s useful\n\n1. Detect broken HEAD requests (often used by monitoring tools or bots).\n\n2. See bandwidth saved, since HEAD requests don’t return full content.\n\n3. Can help identify missing files or scanning activity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "round(increase(nginx_http_response_count_total{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx UP ",
   "type": "timeseries",
   "description": "Status of Nginx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "200 Status",
   "type": "timeseries",
   "description": "This metric shows the number of successful HTTP GET requests (status 200) served by NGINX. It indicates normal traffic and healthy responses from the server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "round(increase(nginx_http_response_count_total{method=\"GET\", status=\"200\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections waiting",
   "type": "timeseries",
   "description": "Connections idle but open, waiting for the next request (keep-alive).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg_over_time(nginx_connections_waiting[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "description": "Total number of clients currently connected to NGINX.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  }
 ]
}